### ISSUE TITLE
More than one session for same router throws exceptions

### ISSUE THREAD

**Issue by nkaliape** [fooelisa/pyiosxr#39]
The open() method calls _enter_xml_mode which calls lock.
When I try to open two instances of connection for the same router (network testing), it throws exception as below:

Traceback (most recent call last):
  File "/auto/cafy_dev/cafykit/lib/python3.4/site-packages/pyIOSXR/iosxr.py", line 472, in lock
    self._execute_rpc(rpc_command)
  File "/auto/cafy_dev/cafykit/lib/python3.4/site-packages/pyIOSXR/iosxr.py", line 412, in _execute_rpc
    raise XMLCLIError(error_msg, self)
pyIOSXR.exceptions.XMLCLIError: 
Original call was: <?xml version="1.0" encoding="UTF-8"?><Request MajorVersion="1" MinorVersion="0"><Lock/></Request>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/auto/cafy_dev/cafykit/lib/python3.4/site-packages/napalm_iosxr/iosxr.py", line 70, in open
    self.device.open()
  File "/auto/cafy_dev/cafykit/lib/python3.4/site-packages/pyIOSXR/iosxr.py", line 171, in open
    self._enter_xml_mode()
  File "/auto/cafy_dev/cafykit/lib/python3.4/site-packages/pyIOSXR/iosxr.py", line 234, in _enter_xml_mode
    self.lock()
  File "/auto/cafy_dev/cafykit/lib/python3.4/site-packages/pyIOSXR/iosxr.py", line 474, in lock
    raise LockError('Unable to enter in configure exclusive mode!', self)
pyIOSXR.exceptions.LockError: Unable to enter in configure exclusive mode!

Possible solutions:
- open sessions and handle lock as optional parameter. When user tries to create one more session with config true - then throw exception
- isolate connection handling vs XML as add on option -  this way the library to support other modes like netconf yang/grpc, telnet and others

**Comment by nkaliape** [comment]
Kindly ignore - lock option already exists :(
